# Generated by Django 5.2 on 2025-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("admin", "admin"),
                ],
                max_length=10,
            ),
        ),
    ]
