# Generated by Django 5.2 on 2025-05-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
            ),
        ),
    ]
