# Generated by Django 5.2 on 2025-05-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(0, "Cash"), (1, "Card"), (3, "Electron pay")],
                        default=0,
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "student_couse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.studentgroup",
                    ),
                ),
            ],
        ),
    ]
