# Generated by Django 5.2 on 2025-05-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='student_couse',
            new_name='student_course',
        ),
    ]
