# Generated by Django 5.2 on 2025-05-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_student_couse_payment_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='student_course',
            new_name='student_group',
        ),
    ]
