# Generated by Django 5.2 on 2025-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_group_teacher_alter_group_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
