# Generated by Django 5.2 on 2025-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentHomework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("file", models.FileField(upload_to="homeworks/")),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "not rejected"),
                            (2, "rejected"),
                            (3, "pass"),
                            (4, "merit"),
                            (5, "distinction"),
                        ],
                        default=3,
                    ),
                ),
                ("teacher_advice", models.TextField()),
                ("sended_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
