# Generated by Django 5.2 on 2025-05-04 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('user', '0002_alter_student_user_alter_teacher_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='homeworks/')),
                ('grade', models.IntegerField()),
                ('teacher_advice', models.TextField()),
                ('sended_at', models.DateField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
