# Generated by Django 5.2 on 2025-05-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("homework", "0001_initial"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
            ),
        ),
        migrations.AddField(
            model_name="studenthomework",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homework.homework"
            ),
        ),
    ]
