# Generated by Django 5.2 on 2025-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.IntegerField(choices=[(0, 'not rejected'), (2, 'rejected'), (3, 'pass'), (4, 'merit'), (5, 'distinction')], default=3),
        ),
    ]
